[server]
headless = true

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#d3a84c"
backgroundColor = "#0a0e16"
secondaryBackgroundColor = "#111a29"
textColor = "#e9eef6"
font = "sans-serif"
